# Etapa 1: build
FROM node:18 AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Etapa 2: producción con nginx
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Copia config opcional de nginx si querés (por defecto sirve SPA bien)
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
